
name: gemini_lens
description: AI Digital Asset Manager with Gemini 3.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.8.3
  intl: ^0.19.0
  equatable: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.3.0
  uuid: ^4.3.0
  lucide_icons: ^0.321.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true
